---
title: "R Notebook"
output: html_notebook
---

```{r}
library(maxLik)
library(xtable)
library(matrixStats)
```

Likelihoods

```{r}
ll_zhang_approx <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  res <- m * log(mu) - (m + phi) * log(mu + phi) + (m + phi - 0.5) * log(m + phi) + 0.5 * log(phi)
  res
}

ll_zhang_approx_grad <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  x <- cbind(log(N),log(n/N))
  d_gamma <- as.numeric((m - mu) / (mu + phi)) * (phi* x )
  d_phi <- -log(mu + phi) - (m + phi)/(mu + phi) + log(m + phi) + (m + phi -0.5) / (m + phi) + 1/(2*phi)
  #d_phi <- -log(m+phi) - (m + phi)/(mu + phi) + log(phi) + 1 + digamma(m+phi)  - digamma(phi)
  cbind(d_gamma, d_phi)
  #c(alpha=d_gamma[1], beta = d_gamma[2], phi=sum(d_phi))
}

ll_zhang_approx_hess <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  x <- cbind(log(N),log(n/N))
  
  #  
  d2_gamma <-  t(x) %*% (x * -as.numeric( (m+phi)/(mu+phi)*phi ))
  d2_phi <- sum( -(2*mu+phi-m)/(mu+phi)^2 + (m+phi +0.5)/(m+phi)^2 - 1/(2*phi^2) )
  d2_gamma_phi <- colSums( -as.numeric( (mu - m) / (mu+phi)^2 * mu) * x)
  
  h <- as.matrix(Matrix::bdiag(d2_gamma, d2_phi))
  colnames(h) <- rownames(h) <- c("alpha","beta","phi")
  h[3,1:2] <- h[1:2,3] <- d2_gamma_phi
  h
}


ll_lgamma <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  res <-  m * log(mu) - (m + phi) * log(mu + phi) + lgamma(m + phi) + phi * log(phi) - lgamma(phi)
  res
}

ll_lgamma_grad <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  x <- cbind(log(N),log(n/N))
  d_gamma <- as.numeric((m - mu) / (mu + phi)) * (phi* x )
  
  #d_phi <- -log(mu + phi) - (m + phi)/(mu + phi) + log(m + phi) + (m + phi -0.5) / (m + phi) + 1/(2*phi)
  d_phi <- - log(m+phi) - (m + phi)/(mu + phi) + log(phi) + 1 + digamma(m+phi)  - digamma(phi)
  cbind(d_gamma, d_phi)
  #c(alpha=d_gamma[1], beta = d_gamma[2], phi=sum(d_phi))
}


ll_nb <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  res <- dnbinom(x = m, size = phi, prob = phi / (phi + mu), log = TRUE)
  res
}

ll_ztnb <- function(param, data) {
  alpha <- param[1]
  beta <- param[2]
  phi <- param[3]
  m <- as.matrix(data$m)
  n <- as.matrix(data$n)
  N <- as.matrix(data$N)
  mu <- N^alpha*(n/N)^beta
  res <- actuar::dztnbinom(x = m, size = phi, prob = phi / (phi + mu), log = TRUE)
  res
}

```

Estimation

```{r}

zhang_coefs_high <- list()
exact_coefs_high <- list()
dnbinom_coefs_high <- list()
ztbinom_coefs_high <- list()

## high variance
for (i in 1:500) {
  set.seed(i)
  
  alpha <- 0.70
  beta <- 0.80
  phi <- 2.5

  m_true <-  c(4, 3, 1, 1, 4, 12, 3, 1, 10, 26, 9, 68, 2, 1, 3, 10, 2, 1, 
1, 1, 11, 19, 4, 2, 1, 1, 1, 1, 2, 3, 1, 23, 1, 6, 85, 1, 4, 
1, 6, 1, 3, 5, 2, 11, 1, 1, 10, 4, 2, 4, 2, 7, 1, 15, 3, 9, 1, 
10, 2, 414, 1, 2, 1, 9, 2, 19, 56, 54, 3, 88, 3, 5, 10, 1, 3, 
3, 1, 4, 1, 13, 5, 1, 1, 2, 28, 1, 486, 53, 1362, 10, 2, 4, 5, 
28, 2, 1, 14, 54, 1, 4)
  
  n_examp <- c(12, 12, 7, 1, 41, 405, 8, 5, 48, 259, 11, 1250, 11, 
  3, 3, 24, 8, 3, 1, 2, 61, 203, 6, 8, 2, 2, 1, 6, 3, 2, 1, 17, 
  1, 1, 178, 4, 18, 3, 28, 1, 24, 16, 11, 43, 3, 1, 16, 13, 11, 
  21, 19, 48, 1, 8, 1, 45, 17, 50, 20, 998, 47, 1, 1, 2, 100, 50, 
  410, 139, 10, 608, 10, 2, 20, 3, 29, 6, 1, 55, 1, 26, 1, 3, 2, 
  8, 319, 3, 2060, 138, 11406, 74, 7, 64, 5, 62, 1, 7, 74, 346, 
  9, 2)

  N_examp <- c(24, 55, 14, 36, 1055, 627, 34, 524, 151, 9198, 95, 
  7155, 528, 30, 449, 300, 23, 135, 52, 11, 1687, 1537, 56, 12, 
  5, 17, 30, 703, 49, 23, 3, 1626, 28, 3220, 1033, 150, 82, 286, 
  50, 103, 42, 26, 406, 549, 42, 10, 88, 19, 115, 164, 178, 78, 
  4, 124, 335, 46, 25, 7378, 1214, 2333, 1239, 433, 153, 283, 347, 
  2001, 995, 2675, 214, 3389, 856, 33, 53, 7, 112, 33, 5, 82, 143, 
  44, 81, 228, 518, 2380, 804, 44, 95331, 498, 65571, 2439, 860, 
  375, 537, 163, 61, 34, 2830, 1962, 202, 81)

  mu_examp <- N_examp^alpha*(n_examp/N_examp)^beta

  m_examp <- rnbinom(n = NROW(n_examp), size = phi, prob = phi/(phi + mu_examp))
  
  ## remove zeros
  zeros <- which(m_examp==0)
  m_examp <- m_examp[-zeros]
  N_examp <- N_examp[-zeros]
  n_examp <- n_examp[-zeros]
  
  m0 <- lm(log(m_examp/N_examp) ~ -1 + log(N_examp) + log(n_examp/N_examp))
  
  compare1 <- maxLik::maxLik(logLik = ll_zhang_approx,  grad = lichun_ll_grad, #hess = ll_zhang_approx_hess, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 

  compare2 <- maxLik::maxLik(logLik = ll_lgamma,  grad = ll_lgamma_grad, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  compare3 <- maxLik::maxLik(logLik = ll_nb, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  compare4 <- maxLik::maxLik(logLik = ll_ztnb, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  zhang_coefs_high[[i]] <- c(compare1$estimate, xi = sum(N_examp^compare1$estimate[1]))
  exact_coefs_high[[i]] <- c(compare2$estimate, xi = sum(N_examp^compare2$estimate[1]))
  dnbinom_coefs_high[[i]] <- c(compare3$estimate, xi = sum(N_examp^compare3$estimate[1]))
  ztbinom_coefs_high[[i]] <- c(compare4$estimate, xi = sum(N_examp^compare4$estimate[1]))
} 


colMeans(do.call('rbind', zhang_coefs_high))
colMeans(do.call('rbind', exact_coefs_high))
colMeans(do.call('rbind', dnbinom_coefs_high))
colMeans(do.call('rbind', ztbinom_coefs_high))


## low 

zhang_coefs_low <- list()
exact_coefs_low <- list()
dnbinom_coefs_low <- list()
ztbinom_coefs_low <- list()

## high variance
for (i in 1:500) {
  set.seed(i)
  
  alpha <- 0.70
  beta <- 0.80
  phi <- 1.5
  xi <- sum(N_examp^alpha)

  n_examp <- c(12, 12, 7, 1, 41, 405, 8, 5, 48, 259, 11, 1250, 11, 
  3, 3, 24, 8, 3, 1, 2, 61, 203, 6, 8, 2, 2, 1, 6, 3, 2, 1, 17, 
  1, 1, 178, 4, 18, 3, 28, 1, 24, 16, 11, 43, 3, 1, 16, 13, 11, 
  21, 19, 48, 1, 8, 1, 45, 17, 50, 20, 998, 47, 1, 1, 2, 100, 50, 
  410, 139, 10, 608, 10, 2, 20, 3, 29, 6, 1, 55, 1, 26, 1, 3, 2, 
  8, 319, 3, 2060, 138, 11406, 74, 7, 64, 5, 62, 1, 7, 74, 346, 
  9, 2)

  N_examp <- c(24, 55, 14, 36, 1055, 627, 34, 524, 151, 9198, 95, 
  7155, 528, 30, 449, 300, 23, 135, 52, 11, 1687, 1537, 56, 12, 
  5, 17, 30, 703, 49, 23, 3, 1626, 28, 3220, 1033, 150, 82, 286, 
  50, 103, 42, 26, 406, 549, 42, 10, 88, 19, 115, 164, 178, 78, 
  4, 124, 335, 46, 25, 7378, 1214, 2333, 1239, 433, 153, 283, 347, 
  2001, 995, 2675, 214, 3389, 856, 33, 53, 7, 112, 33, 5, 82, 143, 
  44, 81, 228, 518, 2380, 804, 44, 95331, 498, 65571, 2439, 860, 
  375, 537, 163, 61, 34, 2830, 1962, 202, 81)

  mu_examp <- N_examp^alpha*(n_examp/N_examp)^beta

  m_examp <- rnbinom(n = NROW(n_examp), size = phi, prob = phi/(phi + mu_examp))
  
  ## remove zeros
  zeros <- which(m_examp==0)
  m_examp <- m_examp[-zeros]
  N_examp <- N_examp[-zeros]
  n_examp <- n_examp[-zeros]
  
  m0 <- lm(log(m_examp/N_examp) ~ -1 + log(N_examp) + log(n_examp/N_examp))
  
  compare1 <- maxLik::maxLik(logLik = ll_zhang_approx,  grad = lichun_ll_grad, #hess = ll_zhang_approx_hess, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 

  compare2 <- maxLik::maxLik(logLik = ll_lgamma,  grad = ll_lgamma_grad, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  compare3 <- maxLik::maxLik(logLik = ll_nb, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  compare4 <- maxLik::maxLik(logLik = ll_ztnb, 
               method = "BFGS",
               start = c(alpha=coef(m0)[1]+1,beta=coef(m0)[2], phi = 1/sigma(m0)), 
               data = data.frame(m=m_examp,n=n_examp, N=N_examp)) 
  
  zhang_coefs_low[[i]] <- c(compare1$estimate, xi = sum(N_examp^compare1$estimate[1]))
  exact_coefs_low[[i]] <- c(compare2$estimate, xi = sum(N_examp^compare2$estimate[1]))
  dnbinom_coefs_low[[i]] <- c(compare3$estimate, xi = sum(N_examp^compare3$estimate[1]))
  ztbinom_coefs_low[[i]] <- c(compare4$estimate, xi = sum(N_examp^compare4$estimate[1]))
} 

```

Calculate statistics

```{r}
sim_study <- bind_rows(
  ## low 
  do.call('rbind',zhang_coefs_low) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "zhang_coefs_low",
         b = row_number()) ,
  do.call('rbind',exact_coefs_low) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "exact_coefs_low",
         b = row_number()),
  do.call('rbind',dnbinom_coefs_low) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "dnbinom_coefs_low",
         b = row_number()),
  do.call('rbind',ztbinom_coefs_low) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "ztbinom_coefs_low",
         b = row_number()),
  ## high
  do.call('rbind',zhang_coefs_high) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "zhang_coefs_high",
         b = row_number()) ,
  do.call('rbind',exact_coefs_high) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "exact_coefs_high",
         b = row_number()),
  do.call('rbind',dnbinom_coefs_high) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "dnbinom_coefs_high",
         b = row_number()),
  do.call('rbind',ztbinom_coefs_high) %>%
  as.data.frame() %>%
  set_names(c("alpha_hat","beta_hat", "phi_hat", "xi_hat")) %>%
  mutate(model = "ztbinom_coefs_high",
         b = row_number())
)

sim_study %>%
  group_by(model) %>%
  summarise(relbias_alpha = mean((alpha_hat-alpha)/alpha)*100,
            relbias_beta = mean((beta_hat-beta)/beta)*100,
            relbias_phi = mean((phi_hat-phi)/phi)*100,
            relbias_xi = mean((xi_hat-xi)/xi)*100,
            mse_alpha = mean( sum(alpha_hat-alpha)^2),
            mse_beta = mean( sum(beta_hat-beta)^2),
            mse_phi = mean( sum(phi_hat-phi)^2),
            mse_xi = mean( sum(xi_hat-xi)^2),
            rrmse_alpha = sqrt(mse_alpha)/alpha*100,
            rrmse_beta = sqrt(mse_beta)/beta*100,
            rrmse_phi = sqrt(mse_phi)/phi*100,
            rrmse_xi = sqrt(mse_xi)/xi*100) %>%
  select(model, relbias_alpha:relbias_xi, rrmse_alpha:rrmse_xi) %>%
  gather(stats, vals, -model) %>%
  separate(stats, c("measure", "param"), sep = "_") %>%
  spread(measure, vals) %>%
  mutate(type = str_extract(model, "high|low")) %>%
  select(type, param, model, relbias, rrmse) %>%
  arrange(type, param, model)  %>%
  xtable(caption = "sfsfsa", label = "tab-sg-basic", digits = 2) %>%
  print.xtable(include.rownames = F, caption = "afasf", caption.placement = "top", format.args = list(big.mark = ","))
```


